apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/health-probe-status-codes: 200-499
    external-dns.alpha.kubernetes.io/hostname: tls-fe.app.mddinternship.com
  labels:
    app: tls-fe
  name: tls-fe-ingres
spec:
  rules:
    - host: tls-fe.app.mddinternship.com
      http:
        paths:
          - frontend:
              service:
                name: tls-fe-service
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - tls-fe.app.mddinternship.com
      secretName: tls-fe-db-tls

---
apiVersion: v1
kind: Service
metadata:
  name: tls-fe-service
spec:
  selector:
    #app.kubernetes.io/name: tls-be
    app: tls-fe
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 4173
---
apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJuZXh1cy50b29sLm1kZGludGVybnNoaXAuY29tIjogewogICAgICAiYXV0aCI6ICJZV1J0YVc0NmJtVjRkWE5CWkcxcGJnPT0iCiAgICB9CiAgfQp9Cg==
kind: Secret
metadata:
  name: nexus-docker
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-fe
  labels:
    app: tls-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-fe
  template:
    metadata:
      labels:
        app: tls-fe
    spec:
      containers:
        - name: bsfrontend
          image: nexus.tool.mddinternship.com/repository/tls-frontend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
      imagePullSecrets:
        - name: nexus-docker
  
